### ISSUE TITLE
Check other courses

### ISSUE THREAD

**Issue by dsmits** [esciencecenter-digital-skills/SICSS-odissei-machine-learning#1]
https://github.com/carpentries-incubator/deep-learning-intro/issues/57

Which courses can we reuse?

**Comment by CunliangGeng** [comment]
## [sk-learn tutorial](https://scikit-learn.org/stable/tutorial/index.html)
- good intro about ML

 
## [C3DIS 2019 - Introduction to Machine Learning](https://injeans.github.io/c3dis-intro-to-ml/index.html)
content
 ![image](https://user-images.githubusercontent.com/9798985/169551216-d6af5933-5b39-4f32-897e-bd22c496ed80.png)
