### ISSUE TITLE
Theory: classification algorithms

### ISSUE THREAD

**Issue by dsmits** [esciencecenter-digital-skills/SICSS-odissei-machine-learning#18]
- Decisiontree
- Nearest neighbor

The regression theory is in file `Theory-on-regression.md`, take a look as a reference before developing classification theory

**Comment by CunliangGeng** [comment]
@dsmits  @dafnevk  We don't have theory for linear classification (logistic regression) but only non-linear ones. And the logistic regression will be referenced in the theory of neural net (for regression), so shall we add logistic regression for classification and maybe remove nearest neighbour?
