### ISSUE TITLE
Theory: Regression algorithms

### ISSUE THREAD

**Issue by dsmits** [esciencecenter-digital-skills/SICSS-odissei-machine-learning#19]
- [Ordinary least squares (linear regression)](https://scikit-learn.org/stable/modules/linear_model.html#ordinary-least-squares)
- Neural net

**Comment by dafnevk** [comment]
He also suggested to say something about L1 regularization. Social Scientists often find it useful to have small, explainable models and L1 helps with this.

**Comment by dafnevk** [comment]
Javier also mentioned that overfitting / out-of-sample prediction / bias-variance trade-off is an important and difficult to understand topic.
As a reference, here's a course on data science that Javier teaches: https://adav-course-2022.netlify.app we could borrow visuals from him.
