### ISSUE TITLE
Check Colins lesson material

### ISSUE THREAD

**Issue by dsmits** [esciencecenter-digital-skills/SICSS-odissei-machine-learning#2]
https://github.com/carpentries-incubator/machine-learning-novice-sklearn

How much time does this cover?
Which parts are reusable for us?

**Comment by CunliangGeng** [comment]
**Time**: 4h

**Content**:
![image](https://user-images.githubusercontent.com/9798985/169552035-73b0d81e-6118-47b9-a3bb-2be2c73ee4da.png)
