### ISSUE TITLE
Check Peters course

### ISSUE THREAD

**Issue by dsmits** [esciencecenter-digital-skills/SICSS-odissei-machine-learning#3]
https://deeplearning540.github.io/

How much time does this cover?
Which parts are reusable for us?

**Comment by CunliangGeng** [comment]
**Time**: 4h

**Content**
- Different types of ML problems and models
	- supervised learning
		- classification
		- regression
	- unsupervised learning
		- clustering
	- reinforcement learning
- Clustering
	- math and algorithm of Nearest Neighbors Clustering
	- `sklearn.cluster.KMeans`
- Classification
	- `sklearn.neighbors.KNeighborsClassifier`
	- `sklearn.metrics.confusion_matrix`
	- `sklearn.metrics.ConfusionMatrixDisplay`
	- `sklearn.metrics.recall_score`
- ROC
	- `sklearn.metrics.roc_curve`
	- `sklearn.metrics.RocCurveDisplay`


**Packages**:
- pandas
- serborn
- scikit-learn

**Dataset**
- [palmerpenguins](https://github.com/allisonhorst/palmerpenguins)
