### ISSUE TITLE
Dev introduction section

### ISSUE THREAD

**Issue by dsmits** [esciencecenter-digital-skills/SICSS-odissei-machine-learning#7]
Develop the introduction section 
Reference material #1, #2, #3, #4

**Comment by CunliangGeng** [comment]
Please review [1-Intro.md](https://github.com/esciencecenter-digital-skills/SICSS-odissei-machine-learning/blob/main/1-Intro.md)

**Comment by dafnevk** [comment]
Looks good!
I'm not so sure about the usefulness of the venn diagram with problems/ai/ML etc. Can become a quite lengthy story and you may not want to end up in discussions about definitions. On the other hand, maybe it helps putting things in context.

I think it would be useful to create slides for this introduction.

**Comment by CunliangGeng** [comment]
Thanks Dafne, the venn diagram of AI-ML intends to give a big picture of AI-ML and their limit.
 Let's discuss how to present the introduction next week.
